[cerebrium.deployment]
name = "mtailor-deployment1"
python_version = "3.10"
docker_base_image_url = "debian:bookworm-slim"

include = [
  "main.py",
  "model.py",
  "classifier.onnx",
  "requirements.txt"
]
exclude = ["__pycache__"]

[cerebrium.hardware]
cpu = 2
memory = 8.0
compute = "CPU"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

